增加安装root限制以及配置config

diff --git a/machineinstall b/machineinstall
--- a/machineinstall
+++ b/machineinstall
@@ -2,6 +2,7 @@
 
 PROGRAM_NAME=$0
 cd `(dirname $PROGRAM_NAME)`
+source machinefunc.sh
 
 function usage()
 {
@@ -20,7 +21,10 @@ Arguments:
 EOF
 }
 
-source machinefunc.sh
+if [[ "$(whoami)" != "root" ]];then
+    error "You need to be root to run installation"
+    exit 1
+fi
 
 if [[ $# == 0 ]];then
     usage
@@ -29,12 +33,8 @@ fi
 
 short_opts="hicp:l"
 long_opts="help,install,clean,part:,list-part,reinstall"
-TEMP=$(getopt -n $PROGRAM_NAME -o "$short_opts" -l "$long_opts" -- "$@")
-
-if [[ $? -ne 0 ]];then
-    error "Error parsing arguments. Try $PROGRAM_NAME --help"
-    exit 1
-fi
+TEMP=$(getopt -n $PROGRAM_NAME -o "$short_opts" -l "$long_opts" -- "$@") || \
+{ error "Error parsing arguments. Try $PROGRAM_NAME --help"; exit 1; }
 
 PART="all"
 EXE=""
